apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        # CRITICAL: This image name 'my-app' MUST match the key used
        # in the 'gcloud deploy releases create --images' command in cloudbuild.yaml.
        - image: my-app
          ports:
            - containerPort: 8080