apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: hashitalks-cloud-run-app

# 1. MANIFESTS section defines HOW to render the YAMLs.
# We use Kustomize here. The base configuration will point to the 'test' overlay by default.
manifests:
  kustomize:
    paths:
      - kustomize/overlays/test

# 2. DEPLOY section defines WHAT to do with the rendered YAMLs.
# We use the Cloud Run deployer.
deploy:
  cloudrun: {}

# 3. PROFILES section uses patches to change the configuration for different environments.
profiles:
  # This profile is for the 'staging' environment.
  - name: staging
    patches:
      # We replace the default Kustomize path with the 'staging' overlay path.
      - op: replace
        path: /manifests/kustomize/paths/0
        value: kustomize/overlays/staging

  # This profile is for the 'production' environment.
  - name: production
    patches:
      # We replace the default Kustomize path with the 'production' overlay path.
      - op: replace
        path: /manifests/kustomize/paths/0
        value: kustomize/overlays/production










# # UPDATED: Using a recent API version is best practice.
# # This ensures we can use the latest features supported by Cloud Deploy's rendering engine.
# apiVersion: skaffold/v4beta13
# kind: Config
# metadata:
#   name: hashitalks-cloud-run-app

# # IMPORTANT: We keep the `googleCloudRun` deployer type.
# # This is the specific integration that Google Cloud Deploy recognizes and uses.
# # We DO NOT add `projectid` or `region` here, as Cloud Deploy injects that
# # information from its Target definitions, allowing this file to be portable.
# deploy:
#   cloudrun: {}

# # The `profiles` section remains the core mechanism for Cloud Deploy to select
# # the correct configuration for each environment (test, staging, production).
# profiles:
#   - name: test
#     deploy:
#       cloudrun: 
#         name: hashitalks-cloud-run-app-test

#   - name: staging
#     deploy:
#       cloudrun:
#         name: hashitalks-cloud-run-app-staging

#   - name: production
#     deploy:
#       cloudrun:
#         name: hashitalks-cloud-run-app-production

# manifests:
#   rawYaml:
#     - service.yaml